// Complete language dataset for Proto-Language application
window.languageData = {
    english: [
        { text: "I/me", weight: 1.0 },
        { text: "You", weight: 0.98 },
        { text: "No", weight: 0.96 },
        { text: "Yes/OK", weight: 0.95 },
        { text: "Water", weight: 0.94 },
        { text: "Food/eat", weight: 0.93 },
        { text: "Good", weight: 0.92 },
        { text: "Bad", weight: 0.91 },
        { text: "Give", weight: 0.9 },
        { text: "Take", weight: 0.89 },
        { text: "See/look", weight: 0.88 },
        { text: "Go", weight: 0.87 },
        { text: "Come", weight: 0.86 },
        { text: "Day", weight: 0.85 },
        { text: "Night", weight: 0.84 },
        { text: "Big", weight: 0.83 },
        { text: "Small", weight: 0.82 },
        { text: "Mother", weight: 0.81 },
        { text: "One/first", weight: 0.8 },
        { text: "Want", weight: 0.79 },
        { text: "Know", weight: 0.78 },
        { text: "Think", weight: 0.77 },
        { text: "Time", weight: 0.76 },
        { text: "Many/much", weight: 0.75 },
        { text: "Child", weight: 0.74 },
        { text: "Father", weight: 0.73 },
        { text: "Woman/female", weight: 0.72 },
        { text: "Man/male", weight: 0.71 },
        { text: "Say/speak", weight: 0.7 },
        { text: "Hand", weight: 0.69 },
        { text: "Heart", weight: 0.68 },
        { text: "Sun", weight: 0.67 },
        { text: "Moon", weight: 0.66 },
        { text: "Fire", weight: 0.65 },
        { text: "Death", weight: 0.64 },
        { text: "Life", weight: 0.63 },
        { text: "Walk", weight: 0.62 },
        { text: "Sleep", weight: 0.61 },
        { text: "Drink", weight: 0.6 },
        { text: "Hot", weight: 0.59 },
        { text: "Cold", weight: 0.58 },
        { text: "Person", weight: 0.57 },
        { text: "Body", weight: 0.56 },
        { text: "Head", weight: 0.55 },
        { text: "Eye", weight: 0.54 },
        { text: "Hear", weight: 0.53 },
        { text: "House/home", weight: 0.52 },
        { text: "New", weight: 0.51 },
        { text: "Old", weight: 0.5 },
        { text: "Blood", weight: 0.49 }
    ],
    hindi: [
        { text: "मैं", transliteration: "main", weight: 1.0 },
        { text: "तुम", transliteration: "tum", weight: 0.98 },
        { text: "नहीं", transliteration: "nahin", weight: 0.96 },
        { text: "हाँ/ठीक है", transliteration: "haan/theek hai", weight: 0.95 },
        { text: "पानी", transliteration: "paani", weight: 0.94 },
        { text: "खाना", transliteration: "khaana", weight: 0.93 },
        { text: "अच्छा", transliteration: "accha", weight: 0.92 },
        { text: "बुरा", transliteration: "bura", weight: 0.91 },
        { text: "देना", transliteration: "dena", weight: 0.9 },
        { text: "लेना", transliteration: "lena", weight: 0.89 },
        { text: "देखो", transliteration: "dekho", weight: 0.88 },
        { text: "जाओ", transliteration: "jao", weight: 0.87 },
        { text: "आओ", transliteration: "aao", weight: 0.86 },
        { text: "दिन", transliteration: "din", weight: 0.85 },
        { text: "रात", transliteration: "raat", weight: 0.84 },
        { text: "बड़ा", transliteration: "bada", weight: 0.83 },
        { text: "छोटा", transliteration: "chota", weight: 0.82 },
        { text: "माँ", transliteration: "maa", weight: 0.81 },
        { text: "एक/पहला", transliteration: "ek/pehla", weight: 0.8 },
        { text: "चाहना", transliteration: "chahna", weight: 0.79 },
        { text: "जानना", transliteration: "jaanna", weight: 0.78 },
        { text: "सोचना", transliteration: "sochna", weight: 0.77 },
        { text: "समय", transliteration: "samay", weight: 0.76 },
        { text: "बहुत", transliteration: "bahut", weight: 0.75 },
        { text: "बच्चा", transliteration: "baccha", weight: 0.74 },
        { text: "पिता", transliteration: "pita", weight: 0.73 },
        { text: "औरत", transliteration: "aurat", weight: 0.72 },
        { text: "आदमी", transliteration: "aadmi", weight: 0.71 },
        { text: "बोलना", transliteration: "bolna", weight: 0.7 },
        { text: "हाथ", transliteration: "haath", weight: 0.69 },
        { text: "दिल", transliteration: "dil", weight: 0.68 },
        { text: "सूरज", transliteration: "suraj", weight: 0.67 },
        { text: "चाँद", transliteration: "chaand", weight: 0.66 },
        { text: "आग", transliteration: "aag", weight: 0.65 },
        { text: "मौत", transliteration: "maut", weight: 0.64 },
        { text: "जिंदगी", transliteration: "zindagi", weight: 0.63 },
        { text: "चलना", transliteration: "chalna", weight: 0.62 },
        { text: "सोना", transliteration: "sona", weight: 0.61 },
        { text: "पीना", transliteration: "peena", weight: 0.6 },
        { text: "गरम", transliteration: "garam", weight: 0.59 },
        { text: "ठंडा", transliteration: "thanda", weight: 0.58 },
        { text: "व्यक्ति", transliteration: "vyakti", weight: 0.57 },
        { text: "शरीर", transliteration: "shareer", weight: 0.56 },
        { text: "सिर", transliteration: "sir", weight: 0.55 },
        { text: "आँख", transliteration: "aankh", weight: 0.54 },
        { text: "सुनना", transliteration: "sunna", weight: 0.53 },
        { text: "घर", transliteration: "ghar", weight: 0.52 },
        { text: "नया", transliteration: "naya", weight: 0.51 },
        { text: "पुराना", transliteration: "purana", weight: 0.5 },
        { text: "खून", transliteration: "khoon", weight: 0.49 }
    ],
    tamil: [
        { text: "நான்", transliteration: "naan", weight: 1.0 },
        { text: "நீ", transliteration: "nee", weight: 0.98 },
        { text: "இல்லை", transliteration: "illai", weight: 0.96 },
        { text: "ஆம்/சரி", transliteration: "aam/sari", weight: 0.95 },
        { text: "தண்ணீர்", transliteration: "thanneer", weight: 0.94 },
        { text: "உணவு/சாப்பிடு", transliteration: "unavu/saapidu", weight: 0.93 },
        { text: "நல்லது", transliteration: "nallathu", weight: 0.92 },
        { text: "கெட்டது", transliteration: "kettadhu", weight: 0.91 },
        { text: "கொடு", transliteration: "kodu", weight: 0.9 },
        { text: "எடு", transliteration: "edu", weight: 0.89 },
        { text: "பார்", transliteration: "paar", weight: 0.88 },
        { text: "போ", transliteration: "po", weight: 0.87 },
        { text: "வா", transliteration: "vaa", weight: 0.86 },
        { text: "நாள்", transliteration: "naal", weight: 0.85 },
        { text: "இரவு", transliteration: "iravu", weight: 0.84 },
        { text: "பெரிய", transliteration: "periya", weight: 0.83 },
        { text: "சிறிய", transliteration: "siriya", weight: 0.82 },
        { text: "அம்மா", transliteration: "amma", weight: 0.81 },
        { text: "ஒன்று/முதல்", transliteration: "ondru/mudhal", weight: 0.8 },
        { text: "வேண்டும்", transliteration: "vendum", weight: 0.79 },
        { text: "தெரியும்", transliteration: "theriyum", weight: 0.78 },
        { text: "நினைக்க", transliteration: "ninaika", weight: 0.77 },
        { text: "நேரம்", transliteration: "neram", weight: 0.76 },
        { text: "நிறைய", transliteration: "niraiya", weight: 0.75 },
        { text: "குழந்தை", transliteration: "kuzhandhai", weight: 0.74 },
        { text: "அப்பா", transliteration: "appa", weight: 0.73 },
        { text: "பெண்", transliteration: "pen", weight: 0.72 },
        { text: "ஆண்", transliteration: "aan", weight: 0.71 },
        { text: "சொல்", transliteration: "sol", weight: 0.7 },
        { text: "கை", transliteration: "kai", weight: 0.69 },
        { text: "இதயம்", transliteration: "idhayam", weight: 0.68 },
        { text: "சூரியன்", transliteration: "suriyan", weight: 0.67 },
        { text: "நிலவு", transliteration: "nilavu", weight: 0.66 },
        { text: "நெருப்பு", transliteration: "neruppu", weight: 0.65 },
        { text: "மரணம்", transliteration: "maranam", weight: 0.64 },
        { text: "வாழ்க்கை", transliteration: "vaazhkai", weight: 0.63 },
        { text: "நட", transliteration: "nada", weight: 0.62 },
        { text: "தூங்கு", transliteration: "thoongu", weight: 0.61 },
        { text: "குடி", transliteration: "kudi", weight: 0.6 },
        { text: "சூடான", transliteration: "soodana", weight: 0.59 },
        { text: "குளிர்", transliteration: "kulir", weight: 0.58 },
        { text: "நபர்", transliteration: "nabar", weight: 0.57 },
        { text: "உடல்", transliteration: "udal", weight: 0.56 },
        { text: "தலை", transliteration: "thalai", weight: 0.55 },
        { text: "கண்", transliteration: "kan", weight: 0.54 },
        { text: "கேள்", transliteration: "kel", weight: 0.53 },
        { text: "வீடு", transliteration: "veedu", weight: 0.52 },
        { text: "புதிய", transliteration: "pudhiya", weight: 0.51 },
        { text: "பழைய", transliteration: "pazhaiya", weight: 0.5 },
        { text: "இரத்தம்", transliteration: "ratham", weight: 0.49 }
    ],
    telugu: [
        { text: "నేను", transliteration: "nenu", weight: 1.0 },
        { text: "నువ్వు", transliteration: "nuvvu", weight: 0.98 },
        { text: "కాదు", transliteration: "kaadu", weight: 0.96 },
        { text: "అవును/సరే", transliteration: "avunu/sare", weight: 0.95 },
        { text: "నీరు", transliteration: "neeru", weight: 0.94 },
        { text: "ఆహారం/తిను", transliteration: "aaharam/tinu", weight: 0.93 },
        { text: "మంచిది", transliteration: "manchidi", weight: 0.92 },
        { text: "చెడ్డది", transliteration: "cheddadi", weight: 0.91 },
        { text: "ఇవ్వు", transliteration: "ivvu", weight: 0.9 },
        { text: "తీసుకో", transliteration: "teesuko", weight: 0.89 },
        { text: "చూడు", transliteration: "choodu", weight: 0.88 },
        { text: "వెళ్ళు", transliteration: "vellu", weight: 0.87 },
        { text: "రా", transliteration: "raa", weight: 0.86 },
        { text: "రోజు", transliteration: "roju", weight: 0.85 },
        { text: "రాత్రి", transliteration: "raatri", weight: 0.84 },
        { text: "పెద్ద", transliteration: "pedda", weight: 0.83 },
        { text: "చిన్న", transliteration: "chinna", weight: 0.82 },
        { text: "అమ్మ", transliteration: "amma", weight: 0.81 },
        { text: "ఒకటి/మొదటి", transliteration: "okati/modati", weight: 0.8 },
        { text: "కావాలి", transliteration: "kaavaali", weight: 0.79 },
        { text: "తెలుసు", transliteration: "telusu", weight: 0.78 },
        { text: "ఆలోచించు", transliteration: "aalochinchu", weight: 0.77 },
        { text: "సమయం", transliteration: "samayam", weight: 0.76 },
        { text: "చాలా", transliteration: "chaala", weight: 0.75 },
        { text: "పిల్లవాడు", transliteration: "pillavadu", weight: 0.74 },
        { text: "నాన్న", transliteration: "naanna", weight: 0.73 },
        { text: "స్త్రీ", transliteration: "stree", weight: 0.72 },
        { text: "పురుషుడు", transliteration: "purushadu", weight: 0.71 },
        { text: "చెప్పు", transliteration: "cheppu", weight: 0.7 },
        { text: "చేయి", transliteration: "cheyi", weight: 0.69 },
        { text: "గుండె", transliteration: "gunde", weight: 0.68 },
        { text: "సూర్యుడు", transliteration: "sooryudu", weight: 0.67 },
        { text: "చంద్రుడు", transliteration: "chandrudu", weight: 0.66 },
        { text: "మంట", transliteration: "manta", weight: 0.65 },
        { text: "మరణం", transliteration: "maranam", weight: 0.64 },
        { text: "జీవితం", transliteration: "jeevitam", weight: 0.63 },
        { text: "నడుచు", transliteration: "naduchu", weight: 0.62 },
        { text: "నిద్ర", transliteration: "nidra", weight: 0.61 },
        { text: "తాగు", transliteration: "taagu", weight: 0.6 },
        { text: "వేడి", transliteration: "vedi", weight: 0.59 },
        { text: "చల్లని", transliteration: "challani", weight: 0.58 },
        { text: "వ్యక్తి", transliteration: "vyakti", weight: 0.57 },
        { text: "శరీరం", transliteration: "sareeram", weight: 0.56 },
        { text: "తల", transliteration: "tala", weight: 0.55 },
        { text: "కన్ను", transliteration: "kannu", weight: 0.54 },
        { text: "విను", transliteration: "vinu", weight: 0.53 },
        { text: "ఇల్లు", transliteration: "illu", weight: 0.52 },
        { text: "కొత్త", transliteration: "kotta", weight: 0.51 },
        { text: "పాత", transliteration: "paata", weight: 0.5 },
        { text: "రక్తం", transliteration: "raktam", weight: 0.49 }
    ],
    bengali: [
        { text: "আমি", transliteration: "ami", weight: 1.0 },
        { text: "তুমি", transliteration: "tumi", weight: 0.98 },
        { text: "না", transliteration: "na", weight: 0.96 },
        { text: "হ্যাঁ/ঠিক আছে", transliteration: "hyan/thik ache", weight: 0.95 },
        { text: "জল", transliteration: "jol", weight: 0.94 },
        { text: "খাবার/খাও", transliteration: "khabar/khao", weight: 0.93 },
        { text: "ভালো", transliteration: "bhalo", weight: 0.92 },
        { text: "খারাপ", transliteration: "kharap", weight: 0.91 },
        { text: "দাও", transliteration: "dao", weight: 0.9 },
        { text: "নাও", transliteration: "nao", weight: 0.89 },
        { text: "দেখো", transliteration: "dekho", weight: 0.88 },
        { text: "যাও", transliteration: "jao", weight: 0.87 },
        { text: "এসো", transliteration: "esho", weight: 0.86 },
        { text: "দিন", transliteration: "din", weight: 0.85 },
        { text: "রাত", transliteration: "raat", weight: 0.84 },
        { text: "বড়", transliteration: "boro", weight: 0.83 },
        { text: "ছোট", transliteration: "choto", weight: 0.82 },
        { text: "মা", transliteration: "ma", weight: 0.81 },
        { text: "এক/প্রথম", transliteration: "ek/prothom", weight: 0.8 },
        { text: "চাই", transliteration: "chai", weight: 0.79 },
        { text: "জানা", transliteration: "jana", weight: 0.78 },
        { text: "ভাবা", transliteration: "bhaba", weight: 0.77 },
        { text: "সময়", transliteration: "somoy", weight: 0.76 },
        { text: "অনেক", transliteration: "onek", weight: 0.75 },
        { text: "বাচ্চা", transliteration: "baccha", weight: 0.74 },
        { text: "বাবা", transliteration: "baba", weight: 0.73 },
        { text: "মহিলা", transliteration: "mohila", weight: 0.72 },
        { text: "পুরুষ", transliteration: "purush", weight: 0.71 },
        { text: "বলা", transliteration: "bola", weight: 0.7 },
        { text: "হাত", transliteration: "haat", weight: 0.69 },
        { text: "হৃদয়", transliteration: "hridoy", weight: 0.68 },
        { text: "সূর্য", transliteration: "surjo", weight: 0.67 },
        { text: "চাঁদ", transliteration: "chand", weight: 0.66 },
        { text: "আগুন", transliteration: "agun", weight: 0.65 },
        { text: "মৃত্যু", transliteration: "mrityu", weight: 0.64 },
        { text: "জীবন", transliteration: "jibon", weight: 0.63 },
        { text: "হাঁটা", transliteration: "hanta", weight: 0.62 },
        { text: "ঘুম", transliteration: "ghum", weight: 0.61 },
        { text: "পান", transliteration: "pan", weight: 0.6 },
        { text: "গরম", transliteration: "gorom", weight: 0.59 },
        { text: "ঠাণ্ডা", transliteration: "thanda", weight: 0.58 },
        { text: "ব্যক্তি", transliteration: "bekti", weight: 0.57 },
        { text: "শরীর", transliteration: "shorir", weight: 0.56 },
        { text: "মাথা", transliteration: "matha", weight: 0.55 },
        { text: "চোখ", transliteration: "chokh", weight: 0.54 },
        { text: "শোনা", transliteration: "shona", weight: 0.53 },
        { text: "বাড়ি", transliteration: "bari", weight: 0.52 },
        { text: "নতুন", transliteration: "notun", weight: 0.51 },
        { text: "পুরানো", transliteration: "purano", weight: 0.5 },
        { text: "রক্ত", transliteration: "rokto", weight: 0.49 }
    ],
    malayalam: [
        { text: "ഞാൻ", transliteration: "njaan", weight: 1.0 },
        { text: "നീ", transliteration: "nee", weight: 0.98 },
        { text: "ഇല്ല", transliteration: "illa", weight: 0.96 },
        { text: "അതെ/ശരി", transliteration: "athe/shari", weight: 0.95 },
        { text: "വെള്ളം", transliteration: "vellam", weight: 0.94 },
        { text: "ഭക്ഷണം/കഴിക്കുക", transliteration: "bhakshanam/kazhikkuka", weight: 0.93 },
        { text: "നല്ലത്", transliteration: "nallath", weight: 0.92 },
        { text: "ചീത്ത", transliteration: "cheetha", weight: 0.91 },
        { text: "തരിക", transliteration: "tharika", weight: 0.9 },
        { text: "എടുക്കുക", transliteration: "edukkuka", weight: 0.89 },
        { text: "നോക്കുക", transliteration: "nokkuka", weight: 0.88 },
        { text: "പോകുക", transliteration: "pokuka", weight: 0.87 },
        { text: "വരിക", transliteration: "varika", weight: 0.86 },
        { text: "പകൽ", transliteration: "pakal", weight: 0.85 },
        { text: "രാത്രി", transliteration: "raathri", weight: 0.84 },
        { text: "വലിയ", transliteration: "valiya", weight: 0.83 },
        { text: "ചെറിയ", transliteration: "cheriya", weight: 0.82 },
        { text: "അമ്മ", transliteration: "amma", weight: 0.81 },
        { text: "ഒന്ന്/ആദ്യം", transliteration: "onnu/aadyam", weight: 0.8 },
        { text: "വേണം", transliteration: "venam", weight: 0.79 },
        { text: "അറിയുക", transliteration: "ariyuka", weight: 0.78 },
        { text: "ചിന്തിക്കുക", transliteration: "chinthikkuka", weight: 0.77 },
        { text: "സമയം", transliteration: "samayam", weight: 0.76 },
        { text: "ധാരാളം", transliteration: "dhaaralam", weight: 0.75 },
        { text: "കുട്ടി", transliteration: "kutti", weight: 0.74 },
        { text: "അച്ഛൻ", transliteration: "achan", weight: 0.73 },
        { text: "സ്ത്രീ", transliteration: "sthree", weight: 0.72 },
        { text: "പുരുഷൻ", transliteration: "purushan", weight: 0.71 },
        { text: "പറയുക", transliteration: "parayuka", weight: 0.7 },
        { text: "കൈ", transliteration: "kai", weight: 0.69 },
        { text: "ഹൃദയം", transliteration: "hridayam", weight: 0.68 },
        { text: "സൂര്യൻ", transliteration: "sooryan", weight: 0.67 },
        { text: "ചന്ദ്രൻ", transliteration: "chandran", weight: 0.66 },
        { text: "തീ", transliteration: "thee", weight: 0.65 },
        { text: "മരണം", transliteration: "maranam", weight: 0.64 },
        { text: "ജീവിതം", transliteration: "jeevitham", weight: 0.63 },
        { text: "നടക്കുക", transliteration: "nadakkuka", weight: 0.62 },
        { text: "ഉറങ്ങുക", transliteration: "uranguka", weight: 0.61 },
        { text: "കുടിക്കുക", transliteration: "kudikkuka", weight: 0.6 },
        { text: "ചൂട്", transliteration: "chooth", weight: 0.59 },
        { text: "തണുപ്പ്", transliteration: "thanuppu", weight: 0.58 },
        { text: "വ്യക്തി", transliteration: "vyakthi", weight: 0.57 },
        { text: "ശരീരം", transliteration: "shareeram", weight: 0.56 },
        { text: "തല", transliteration: "thala", weight: 0.55 },
        { text: "കണ്ണ്", transliteration: "kannu", weight: 0.54 },
        { text: "കേൾക്കുക", transliteration: "kelkkuka", weight: 0.53 },
        { text: "വീട്", transliteration: "veedu", weight: 0.52 },
        { text: "പുതിയ", transliteration: "puthiya", weight: 0.51 },
        { text: "പുതിയ", transliteration: "puthiya", weight: 0.51 },
        { text: "പഴയ", transliteration: "pazhaya", weight: 0.5 },
        { text: "രക്തം", transliteration: "raktham", weight: 0.49 }
    ],
    kannada: [
        { text: "ನಾನು", transliteration: "naanu", weight: 1.0 },
        { text: "ನೀನು", transliteration: "neenu", weight: 0.98 },
        { text: "ಇಲ್ಲ", transliteration: "illa", weight: 0.96 },
        { text: "ಹೌದು/ಸರಿ", transliteration: "haudu/sari", weight: 0.95 },
        { text: "ನೀರು", transliteration: "neeru", weight: 0.94 },
        { text: "ಆಹಾರ/ತಿನ್ನು", transliteration: "aahaara/tinnu", weight: 0.93 },
        { text: "ಒಳ್ಳೆಯದು", transliteration: "olleyadu", weight: 0.92 },
        { text: "ಕೆಟ್ಟದು", transliteration: "kettadu", weight: 0.91 },
        { text: "ಕೊಡು", transliteration: "kodu", weight: 0.9 },
        { text: "ತೆಗೆದುಕೊ", transliteration: "tegeduko", weight: 0.89 },
        { text: "ನೋಡು", transliteration: "nodu", weight: 0.88 },
        { text: "ಹೋಗು", transliteration: "hogu", weight: 0.87 },
        { text: "ಬಾ", transliteration: "baa", weight: 0.86 },
        { text: "ದಿನ", transliteration: "dina", weight: 0.85 },
        { text: "ರಾತ್ರಿ", transliteration: "raatri", weight: 0.84 },
        { text: "ದೊಡ್ಡ", transliteration: "dodda", weight: 0.83 },
        { text: "ಚಿಕ್ಕ", transliteration: "chikka", weight: 0.82 },
        { text: "ಅಮ್ಮ", transliteration: "amma", weight: 0.81 },
        { text: "ಒಂದು/ಮೊದಲ", transliteration: "ondu/modala", weight: 0.8 },
        { text: "ಬೇಕು", transliteration: "beku", weight: 0.79 },
        { text: "ಗೊತ್ತು", transliteration: "gottu", weight: 0.78 },
        { text: "ಯೋಚಿಸು", transliteration: "yochisu", weight: 0.77 },
        { text: "ಸಮಯ", transliteration: "samaya", weight: 0.76 },
        { text: "ಹೆಚ್ಚು", transliteration: "hecchu", weight: 0.75 },
        { text: "ಮಗು", transliteration: "magu", weight: 0.74 },
        { text: "ಅಪ್ಪ", transliteration: "appa", weight: 0.73 },
        { text: "ಹೆಂಗಸು", transliteration: "hengasu", weight: 0.72 },
        { text: "ಗಂಡಸು", transliteration: "gandasu", weight: 0.71 },
        { text: "ಹೇಳು", transliteration: "helu", weight: 0.7 },
        { text: "ಕೈ", transliteration: "kai", weight: 0.69 },
        { text: "ಹೃದಯ", transliteration: "hrudaya", weight: 0.68 },
        { text: "ಸೂರ್ಯ", transliteration: "soorya", weight: 0.67 },
        { text: "ಚಂದ್ರ", transliteration: "chandra", weight: 0.66 },
        { text: "ಬೆಂಕಿ", transliteration: "benki", weight: 0.65 },
        { text: "ಸಾವು", transliteration: "saavu", weight: 0.64 },
        { text: "ಜೀವನ", transliteration: "jeevana", weight: 0.63 },
        { text: "ನಡೆ", transliteration: "nade", weight: 0.62 },
        { text: "ನಿದ್ರೆ", transliteration: "nidre", weight: 0.61 },
        { text: "ಕುಡಿ", transliteration: "kudi", weight: 0.6 },
        { text: "ಬಿಸಿ", transliteration: "bisi", weight: 0.59 },
        { text: "ತಣ್ಣನೆ", transliteration: "tannane", weight: 0.58 },
        { text: "ವ್ಯಕ್ತಿ", transliteration: "vyakti", weight: 0.57 },
        { text: "ದೇಹ", transliteration: "deha", weight: 0.56 },
        { text: "ತಲೆ", transliteration: "tale", weight: 0.55 },
        { text: "ಕಣ್ಣು", transliteration: "kannu", weight: 0.54 },
        { text: "ಕೇಳು", transliteration: "kelu", weight: 0.53 },
        { text: "ಮನೆ", transliteration: "mane", weight: 0.52 },
        { text: "ಹೊಸ", transliteration: "hosa", weight: 0.51 },
        { text: "ಹಳೆಯ", transliteration: "haleya", weight: 0.5 },
        { text: "ರಕ್ತ", transliteration: "rakta", weight: 0.49 }
    ]
};

// Font mapping configuration
window.fontMapping = {
    english: "font-indo",
    hindi: "font-hindi",
    tamil: "font-tamil",
    telugu: "font-telugu",
    bengali: "font-bengali",
    malayalam: "font-malayalam",
    kannada: "font-kannada"
};

// Example usage database (for demonstration purposes)
window.usageExamples = {
    // Examples for "I/me" in each language pair
    english_0_hindi: [
        {
            primary: "I am learning Hindi.",
            secondary: "मैं हिंदी सीख रहा हूँ।"
        },
        {
            primary: "Give me the book.",
            secondary: "मुझे किताब दो।"
        }
    ],
    english_0_tamil: [
        {
            primary: "I want to visit Chennai.",
            secondary: "நான் சென்னைக்கு செல்ல விரும்புகிறேன்."
        },
        {
            primary: "Can you help me?",
            secondary: "நீங்கள் எனக்கு உதவ முடியுமா?"
        }
    ],

    // Examples for "Water" in different language pairs
    english_4_hindi: [
        {
            primary: "Please give me some water.",
            secondary: "कृपया मुझे कुछ पानी दें।"
        },
        {
            primary: "The water is very clean.",
            secondary: "पानी बहुत साफ है।"
        }
    ],
    english_4_tamil: [
        {
            primary: "Is this drinking water?",
            secondary: "இது குடிநீரா?"
        },
        {
            primary: "Water is essential for life.",
            secondary: "உயிர் வாழ தண்ணீர் அவசியம்."
        }
    ],

    // Generate placeholder usage examples for any combination
    getExamples: function (primary, secondary, index) {
        const key = `${primary}_${index}_${secondary}`;

        // Return actual examples if available
        if (this[key]) return this[key];

        // Generate placeholder examples
        const primaryWord = window.languageData[primary][index].text;
        const secondaryWord = window.languageData[secondary][index].text;

        return [
            {
                primary: `Example sentence with "${primaryWord}".`,
                secondary: `Example sentence with "${secondaryWord}".`
            },
            {
                primary: `Another usage of "${primaryWord}" in context.`,
                secondary: `Another usage of "${secondaryWord}" in context.`
            }
        ];
    }
};

// Usage: call this function to get the app working
function initializeProtoLanguageApp() {
    console.log("Proto-Language Cross-Learning App initialized!");

    // This would typically be called from the main HTML file
    // It makes sure all the data is loaded and accessible
    if (typeof window.createStars === 'function') {
        window.createStars();
        window.updateTicker();
        window.updateWordDisplay();

        if (window.isAnimating) {
            window.startWordAnimation();
        }
    }
}